/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cr_myjni_MyJNI */

#ifndef _Included_cr_myjni_MyJNI
#define _Included_cr_myjni_MyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cr_myjni_MyJNI
 * Method:    GetNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cr_myjni_MyJNI_GetNumber
  (JNIEnv *, jobject);

/*
 * Class:     cr_myjni_MyJNI
 * Method:    GetNumber2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cr_myjni_MyJNI_GetNumber2
  (JNIEnv *, jclass);

/*
 * Class:     cr_myjni_MyJNI
 * Method:    GetNumber3
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cr_myjni_MyJNI_GetNumber3
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
